require_relative '../lib/mysql/connection'
require_relative '../lib/mysql/user'
require_relative '../lib/mysql/word'
require_relative '../lib/mysql/questionType'
require_relative '../lib/mysql/session'
require_relative '../lib/mysql/itemType'
require_relative '../lib/mysql/questionSetType'
require_relative '../lib/mysql/questionSet'
require_relative '../lib/mysql/question'
require_relative '../lib/mysql/amateur'

